services:
  app:
    image: fdiary-front-dev
    build:
      context: ./flight-diary-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./flight-diary-frontend:/usr/src/app
    container_name: fdiary-front-dev

  server:
    image: fdiary-backend-dev
    build:
      context: ./flight-diary-backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./flight-diary-backend:/usr/src/app
    container_name: fdiary-backend-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
